using HTTP, Printf, Dates

# Downloads the observed series the model is calibrated against and rewrites the two data
# files in the repository root. Run by hand when a newer data vintage is wanted; the files
# themselves are committed, so a normal model run needs no network access.

tempsources(lastyear) = [
    # name, url, year column, value column, delimiter, published baseline
    (:GISS, "https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.csv",
        1, 14, ',', "1951-1980"),
    (:HADCRUT5, "https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT.5.0.2.0/analysis/diagnostics/HadCRUT.5.0.2.0.analysis.summary_series.global.annual.csv",
        1, 2, ',', "1961-1990"),
    (:NOAA, "https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/global/time-series/globe/land_ocean/12/12/1880-$lastyear/data.csv",
        1, 2, ',', "1901-2000")
]

concentrationsources() = [
    (g, "https://gml.noaa.gov/webdata/ccgg/trends/$(lowercase(string(g)))/$(lowercase(string(g)))_annmean_gl.txt",
        1, 2, isspace, unit) for (g, unit) in zip(GAS3, ["ppm", "ppb", "ppb"])]

# Pull (year, value) pairs out of a downloaded text file. Header, comment and incomplete
# rows are skipped by simply requiring both columns to parse as numbers.
function readyearcolumn(url, yearcol, valuecol, delim)
    series = Dict{Int,Float64}()
    for line in readlines(IOBuffer(HTTP.get(url).body))
        cols = split(line, delim, keepempty=false)
        length(cols) < max(yearcol, valuecol) && continue
        year = tryparse(Int, cols[yearcol])
        value = tryparse(Float64, cols[valuecol])
        year === nothing || value === nothing || (series[year] = value)
    end
    isempty(series) && error("No data parsed from $url.")
    return series
end

function writeobservations(filename, sources, series, lastyear)
    years = minimum(minimum(keys(s)) for s in series):lastyear
    open(joinpath(@__DIR__, "..", filename), "w") do f
        println(f, "# Downloaded by importobservations() on ", Dates.today(), ".")
        for ((name, url, _, _, _, note), s) in zip(sources, series)
            println(f, "# $name [$note], $(minimum(keys(s)))-$(maximum(keys(s))): $url")
        end
        println(f, rstrip(@sprintf("%-6s", "YEAR") * join((@sprintf("%-14s", s[1]) for s in sources))))
        for y in years
            println(f, rstrip(@sprintf("%-6d", y) * join((@sprintf("%-14.6f", get(s, y, NaN)) for s in series))))
        end
    end
    println("File $filename written for $(years[1])-$lastyear.")
end

# lastyear: last complete calendar year in the sources (all of them are annual means).
function importobservations(lastyear::Int=BASEYEAR+1)
    temps = tempsources(lastyear)
    concs = concentrationsources()
    read1(s) = readyearcolumn(s[2], s[3], s[4], s[5])
    writeobservations("AnnualTemperatures.dat", temps, read1.(temps), lastyear)
    writeobservations("AnnualConcentrations.dat", concs, read1.(concs), lastyear)
    println("Now restart Julia and run makecalibrationcache() and writebaseyearemissions().")
end

# The observed global anthropogenic emissions in the model's base year, which the web
# interface harmonizes the SSP scenarios to. Units are the ones the interface works in:
# GtCO2/year for the two CO2 streams, Mt CH4/year and Mt N/year for the other two.
# Reads the data files rather than the loaded constants, so it can follow importobservations()
# in the same session.
function writebaseyearemissions()
    _, _, _, _, _, _, histEmissions = historicdata()
    budget = readfixedwidth(joinpath(@__DIR__, "..", "GlobalCarbonBudget.dat"), comments=true)
    i = findfirst(isequal(BASEYEAR), Int.(budget[:YEAR]))
    i === nothing && error("The carbon budget data ends before $BASEYEAR.")
    emissions = Dict(
        "FossilCO2" => budget[:FOSSIL][i] * 44/12,
        "OtherCO2" => budget[:LANDUSE][i] * 44/12,
        "CH4" => histEmissions[:CH4][iyear(BASEYEAR)] - NATURALCH4,
        "N2O" => histEmissions[:N2O][iyear(BASEYEAR)] - NATURALN2O
    )
    filename = joinpath(@__DIR__, "..", "ui", "js", "data", "baseYearEmissions.js")
    open(filename, "w") do f
        println(f, "// File automatically generated by writebaseyearemissions() in src/importobservations.jl.")
        println(f, "//")
        println(f, "// Observed global anthropogenic emissions in the model's base year $BASEYEAR, in the units")
        println(f, "// the interface sends to the model: GtCO2/year, Mt CH4/year and Mt N/year. CO2 is from the")
        println(f, "// Global Carbon Budget; CH4 and N2O are the emissions that reproduce the observed")
        println(f, "// concentrations, so they include no inventory of their own.")
        println(f, "export const BASE_YEAR_EMISSIONS = {")
        for gas in ["FossilCO2", "OtherCO2", "CH4", "N2O"]
            println(f, @sprintf("    %s: %.6g,", gas, emissions[gas]))
        end
        println(f, "};")
    end
    println("File $filename written: ", emissions)
end

# Global population history, read from the UN World Population Prospects workbook that has
# been sitting unused in RCP/. Sheet1 of that file already holds the world total as a single
# 1950-2100 row; the country sheets would need a country-to-region mapping that this
# repository only has for CO2. Values are estimates up to 2015 and the medium variant after
# that (the file is the 2017 revision), which is why the series is only used as background.
function worldpopulation(years)
    file = joinpath(@__DIR__, "..", "RCP", "UN World Population Prospects 2017 Revision.xlsx")
    data = XLSX.readdata(file, "Sheet1", "C14:EW16")
    wppyears = round.(Int, data[1,:])
    wppyears[1] == 1950 || error("Unexpected layout in $file: row 14 starts at $(wppyears[1]).")
    index = Dict(y => i for (i,y) in enumerate(wppyears))
    return [haskey(index, y) ? data[3,index[y]]/1e6 : NaN for y in years]   # thousands -> billions
end

# The observed global history that the web interface draws behind its projections, in the
# units the figures plot. Every series here is global: the repository has no regional record
# for anything but fossil CO2, which the interface already gets from emission_history.js.
function writeobservedhistory(firstyear::Int=1959)
    _, _, _, _, hTemp, hConc, hEmissions, _ = historicdata()
    budget = readfixedwidth(joinpath(@__DIR__, "..", "GlobalCarbonBudget.dat"), comments=true)
    years = firstyear:BASEYEAR
    index = Dict(round(Int, y) => i for (i,y) in enumerate(budget[:YEAR]))
    gcb(col, y) = haskey(index, y) ? budget[col][index[y]] * 44/12 : NaN   # GtC -> GtCO2

    population = worldpopulation(years)
    fossil = [gcb(:FOSSIL, y) for y in years]
    landuse = [gcb(:LANDUSE, y) for y in years]

    series = [
        "Population"       => population,
        "OtherCO2"         => landuse,
        "CH4"              => [hEmissions[:CH4][iyear(y)] - NATURALCH4 for y in years],
        "N2O"              => [hEmissions[:N2O][iyear(y)] - NATURALN2O for y in years],
        "PerCapitaCO2"     => (fossil .+ landuse) ./ population,
        "CO2concentration" => [hConc[:CO2][iyear(y)] for y in years],
        "CH4concentration" => [hConc[:CH4][iyear(y)] for y in years],
        "N2Oconcentration" => [hConc[:N2O][iyear(y)] for y in years],
        "Temperature"      => [hTemp[iyear(y)] for y in years]
    ]

    filename = joinpath(@__DIR__, "..", "ui", "js", "data", "observedHistory.js")
    open(filename, "w") do f
        println(f, "// File automatically generated by writeobservedhistory() in src/importobservations.jl.")
        println(f, "//")
        println(f, "// Observed global history for $firstyear-$BASEYEAR, one series per figure, in the units the")
        println(f, "// interface plots: billions of people, GtCO2/year, MtCH4/year, MtN/year, tCO2/person/year,")
        println(f, "// ppm, ppb, ppb and degrees above the $(BASELINEYEARS[1])-$(BASELINEYEARS[end]) mean. Sources are the same ones the")
        println(f, "// model is calibrated against: the Global Carbon Budget for land-use CO2, the spliced")
        println(f, "// RCP/NOAA GML concentration record, GISS/HadCRUT5/NOAA for temperature, and the CH4 and")
        println(f, "// N2O emissions that reproduce the observed concentrations. Population is the UN World")
        println(f, "// Population Prospects 2017 revision, estimates to 2015 and medium variant after that.")
        println(f, "//")
        println(f, "// Fossil CO2 is not here: the interface already has it, by region, in emission_history.js.")
        println(f, "export const OBSERVED_HISTORY_START = $firstyear;")
        println(f, "export const OBSERVED_HISTORY = {")
        for (name, values) in series
            numbers = join((isnan(v) ? "null" : @sprintf("%.6g", v) for v in values), ", ")
            println(f, "    $name: [$numbers],")
        end
        println(f, "};")
    end
    println("File $filename written for $firstyear-$BASEYEAR.")
end
